// Generated using SwiftGen, by O.Halligon — https://github.com/AliSoftware/SwiftGen

#if os(iOS) || os(tvOS) || os(watchOS)
  import UIKit.UIImage
  typealias Image = UIImage
#elseif os(OSX)
  import AppKit.NSImage
  typealias Image = NSImage
#endif

enum Asset: String {
    case Ic_radio_btn_blank = "ic_radio_btn_blank"
    case Ic_radio_btn_fill = "ic_radio_btn_fill"
  case Fitness = "fitness"
  case Foodnnutri = "foodnnutri"
  case Foodpics = "foodpics"
  case Ic_back = "ic_back"
  case Ic_blue = "ic_blue"
  case Ic_blue_box = "ic_blue_box"
  case Ic_cast = "ic_cast"
  case Ic_cast_small = "ic_cast_small"
  case Ic_cross = "ic_cross"
  case Ic_dd_down = "ic_dd_down"
  case Ic_down = "ic_down"
  case Ic_drawer = "ic_drawer"
  case Ic_expand = "ic_expand"
  case Ic_lock = "ic_lock"
  case Ic_look = "ic_look"
  case Ic_menu = "ic_menu"
  case Ic_msg = "ic_msg"
  case Ic_msg_notific = "ic_msg_notific"
  case Ic_pause = "ic_pause"
  case Ic_play_big = "ic_play_big"
  case Ic_play_small = "ic_play_small"
  case Ic_red = "ic_red"
  case Ic_redbox = "ic_redbox"
  case Ic_reset = "ic_reset"
  case Ic_send = "ic_send"
  case Ic_shrink = "ic_shrink"
  case Ic_up = "ic_up"
  case Lesson = "lesson"
  case Mfm_Logo = "mfm logo"
  case Oval_13 = "Oval 13"
  case Selfie = "selfie"
  case Weighin = "weighin"
  case Ic_add = "ic_add"
  case IC_add_client = "IC_add_client"
  case Ic_blue_dot = "ic_blue_dot"
  case Ic_blue_pupup = "ic_blue_pupup"
  case Ic_broadcastLarge = "ic_broadcastLarge"
  case Ic_chat_notific = "ic_chat_notific"
  case Ic_client_small = "ic_client_small"
  case Ic_clients = "ic_clients"
  case Ic_eye = "ic_eye"
  case Ic_frwd = "ic_frwd"
  case Ic_frwd_blue = "ic_frwd_blue"
  case Ic_lessons = "ic_lessons"
  case Ic_lessons_small = "ic_lessons_small"
  case Ic_list = "ic_list"
  case Ic_popup = "ic_popup"
  case Ic_red_dot = "ic_red_dot"
  case Ic_reddot_date = "ic_reddot_date"
  case Ic_reddot_map = "ic_reddot_map"
  case Ic_small_Cross = "ic_small cross"
  case Ic_trainer = "ic_trainer"
  case Ill_fitness = "ill_fitness"
  case Rectangle_19_Copy_2 = "Rectangle 19 Copy 2"
  case Heart_Logo = "heart logo"
  case Ic_broadcast = "ic_broadcast"
  case Ic_burger = "ic_burger"
  case Ic_chat_left = "ic_chat_left"
  case Ic_chat_right = "ic_chat_right"
  case Ic_Clients = "ic_Clients"
  case Ic_fitness = "ic_fitness"
  case Ic_food_pics = "ic_food_pics"
  case Ic_lesson = "ic_lesson"
  case Ic_lessonsSmall = "ic_lessonsSmall"
  case Ic_message = "ic_message"
  case Ic_new_broadcast = "ic_new_broadcast"
  case Ic_nutrition = "ic_nutrition"
  case Ic_plus = "ic_plus"
  case Ic_profile = "ic_profile"
  case Ic_settings = "ic_settings"
  case Ic_weigh_In = "ic_weigh-in"
  case Person_Subtract = "person-subtract"
  case Oval_14_Copy_4 = "Oval 14 Copy 4"
  case Oval_Copy_2 = "Oval Copy 2"
  case Oval = "Oval"
  case Ic_check = "ic_check"
  case Ic_close = "ic_close"
  case Ic_flash_auto = "ic_flash_auto"
  case Ic_flash_off = "ic_flash_off"
  case Ic_flash_on = "ic_flash_on"
  case Ic_insert_photo = "ic_insert_photo"
  case Ic_loop = "ic_loop"
  case Ic_photo_camera = "ic_photo_camera"
  case Ic_radio_button_checked = "ic_radio_button_checked"
  case Ic_videocam = "ic_videocam"
  case Shutter_button = "shutter_button"
  case Video_button = "video_button"
  case Video_button_rec = "video_button_rec"
  case Cm_add_white = "cm_add_white"
  case Cm_arrow_back_white = "cm_arrow_back_white"
  case Cm_arrow_downward_white = "cm_arrow_downward_white"
  case Cm_audio_library_white = "cm_audio_library_white"
  case Cm_audio_white = "cm_audio_white"
  case Cm_bell_white = "cm_bell_white"
  case Cm_check_white = "cm_check_white"
  case Cm_close_white = "cm_close_white"
  case Cm_image_white = "cm_image_white"
  case Cm_menu_white = "cm_menu_white"
  case Cm_microphone_white = "cm_microphone_white"
  case Cm_more_horiz_white = "cm_more_horiz_white"
  case Cm_more_vert_white = "cm_more_vert_white"
  case Cm_movie_white = "cm_movie_white"
  case Cm_pause_white = "cm_pause_white"
  case Cm_pen_white = "cm_pen_white"
  case Cm_photo_camera_white = "cm_photo_camera_white"
  case Cm_photo_library_white = "cm_photo_library_white"
  case Cm_play_white = "cm_play_white"
  case Cm_search_white = "cm_search_white"
  case Cm_settings_white = "cm_settings_white"
  case Cm_share_white = "cm_share_white"
  case Cm_shuffle_white = "cm_shuffle_white"
  case Cm_skip_backward_white = "cm_skip_backward_white"
  case Cm_skip_forward_white = "cm_skip_forward_white"
  case Cm_star_white = "cm_star_white"
  case Cm_videocam_white = "cm_videocam_white"
  case Cm_volume_high_white = "cm_volume_high_white"
  case Cm_volume_medium_white = "cm_volume_medium_white"
  case Cm_volume_off_white = "cm_volume_off_white"
  case Ic_add_circle_outline_white = "ic_add_circle_outline_white"
  case Ic_add_circle_white = "ic_add_circle_white"
  case Ic_add_white = "ic_add_white"
  case Ic_arrow_back_white = "ic_arrow_back_white"
  case Ic_arrow_downward_white = "ic_arrow_downward_white"
  case Ic_audiotrack_white = "ic_audiotrack_white"
  case Ic_check_white = "ic_check_white"
  case Ic_close_white = "ic_close_white"
  case Ic_edit_white = "ic_edit_white"
  case Ic_favorite_border_white = "ic_favorite_border_white"
  case Ic_favorite_white = "ic_favorite_white"
  case Ic_history_white = "ic_history_white"
  case Ic_home_white = "ic_home_white"
  case Ic_image_white = "ic_image_white"
  case Ic_menu_white = "ic_menu_white"
  case Ic_more_horiz_white = "ic_more_horiz_white"
  case Ic_more_vert_white = "ic_more_vert_white"
  case Ic_movie_white = "ic_movie_white"
  case Ic_photo_camera_white = "ic_photo_camera_white"
  case Ic_photo_library_white = "ic_photo_library_white"
  case Ic_place_white = "ic_place_white"
  case Ic_search_white = "ic_search_white"
  case Ic_settings_white = "ic_settings_white"
  case Ic_share_white = "ic_share_white"
  case Ic_star_border_white = "ic_star_border_white"
  case Ic_star_half_white = "ic_star_half_white"
  case Ic_star_white = "ic_star_white"
  case Ic_videocam_white = "ic_videocam_white"
  case Ic_visibility_white = "ic_visibility_white"

  var image: Image {
    return Image(asset: self)
  }
}

extension Image {
  convenience init!(asset: Asset) {
    self.init(named: asset.rawValue)
  }
}
